In [1]:
import os
import cv2
import numpy as np
import pickle as pkl
import json

In [33]:
data = {}
pothole_category = [1, 2, 6, 7, 8, 9]

In [34]:
def data2pkl(file_name):
    wo_jpg = file_name.split('.')[0]
    w_json = wo_jpg + ('.json')
    direction = file_name.split('_')[2] #direction
    print(direction)
    
    if direction == 'F':
        image2matrix = cv2.imread(file_name, cv2.IMREAD_COLOR)
    else:
        image2matrix = cv2.imread(file_name, cv2.IMREAD_GRAYSCALE)
    image2matrix = image2matrix / 255.0
    image2matrix = image2matrix - np.mean(image2matrix)
    image2matrix_np = np.array(image2matrix)
    
    with open(w_json, 'r', encoding='utf-8') as json_file:
        json_data = json.load(json_file)

    category_ids = set()
    for annotation in json_data['annotations']:
        category_ids.add(annotation['category_id'])
    
    print(category_ids)
    pothole_sign = False
    for category_id in category_ids:
        if category_id in pothole_category:
            data[file_name] = {
                'matrix' : image2matrix_np,
                'direction' : direction,
                'pothole' : 1
            }
            pothole_sign = True
            continue
    if not pothole_sign:
        data[file_name] = {
            'matrix' : image2matrix,
            'direction' : direction,
            'pothole' : 0
        }

In [35]:
file_name = 'G_A_F_01_0822082218210.jpg'
data2pkl(file_name=file_name)

F
{16, 17}


In [39]:
os.getcwd()

'c:\\Users\\hwnam\\Desktop\\tmp\\Suwon_pothole\\data\\image_data'

In [31]:
data

{'G_A_F_01_0822082218210.jpg': {'matrix': array([[[ 0.07315442,  0.09276226,  0.09668383],
          [ 0.07707599,  0.09668383,  0.1006054 ],
          [ 0.06138971,  0.08491913,  0.08099756],
          ...,
          [ 0.00648775, -0.00135538, -0.00135538],
          [ 0.01433089,  0.00648775,  0.00648775],
          [ 0.03001716,  0.02217403,  0.02217403]],
  
         [[ 0.06923285,  0.08884069,  0.09276226],
          [ 0.08099756,  0.1006054 ,  0.10452697],
          [ 0.06923285,  0.09276226,  0.08884069],
          ...,
          [ 0.01040932,  0.00256618,  0.00256618],
          [ 0.01825246,  0.01040932,  0.01040932],
          [ 0.03001716,  0.02217403,  0.02217403]],
  
         [[ 0.06923285,  0.08884069,  0.09276226],
          [ 0.08099756,  0.1006054 ,  0.10452697],
          [ 0.08491913,  0.10452697,  0.1006054 ],
          ...,
          [ 0.01825246,  0.01040932,  0.01040932],
          [ 0.0260956 ,  0.01825246,  0.01825246],
          [ 0.0260956 ,  0.01825246,  0.

In [32]:
print(data['G_A_F_01_0822082218210.jpg']['matrix'])

[[[ 0.07315442  0.09276226  0.09668383]
  [ 0.07707599  0.09668383  0.1006054 ]
  [ 0.06138971  0.08491913  0.08099756]
  ...
  [ 0.00648775 -0.00135538 -0.00135538]
  [ 0.01433089  0.00648775  0.00648775]
  [ 0.03001716  0.02217403  0.02217403]]

 [[ 0.06923285  0.08884069  0.09276226]
  [ 0.08099756  0.1006054   0.10452697]
  [ 0.06923285  0.09276226  0.08884069]
  ...
  [ 0.01040932  0.00256618  0.00256618]
  [ 0.01825246  0.01040932  0.01040932]
  [ 0.03001716  0.02217403  0.02217403]]

 [[ 0.06923285  0.08884069  0.09276226]
  [ 0.08099756  0.1006054   0.10452697]
  [ 0.08491913  0.10452697  0.1006054 ]
  ...
  [ 0.01825246  0.01040932  0.01040932]
  [ 0.0260956   0.01825246  0.01825246]
  [ 0.0260956   0.01825246  0.01825246]]

 ...

 [[-0.27978676 -0.27978676 -0.27978676]
  [-0.27978676 -0.27978676 -0.27978676]
  [-0.27978676 -0.27978676 -0.27978676]
  ...
  [-0.27978676 -0.27978676 -0.27978676]
  [-0.27978676 -0.27978676 -0.27978676]
  [-0.27978676 -0.27978676 -0.27978676]]

 [

In [38]:
import shutil

os.chdir('image_data')
for image in os.listdir('.'):
    shutil.move(image, '../unzip/' + image)

In [40]:
os.chdir('../label_data')
for label in os.listdir('.'):
    shutil.move(label, '../unzip/' + label)

In [42]:
len(os.listdir('../unzip'))

419285